from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import date
from src.config import insertEmployee
from src.config import insertPatient
class Ui_Insert(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(128,128,128)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.employeeName = QtWidgets.QLineEdit(self.centralwidget)
        self.employeeName.setGeometry(QtCore.QRect(90, 90, 181, 31))
        self.employeeName.setStyleSheet("background-color:white")
        self.employeeName.setObjectName("employeeName")
        self.employeeBirth = QtWidgets.QLineEdit(self.centralwidget)
        self.employeeBirth.setGeometry(QtCore.QRect(90, 140, 181, 31))
        self.employeeBirth.setStyleSheet("background-color:white")
        self.employeeBirth.setObjectName("employeeBirth")
        self.employeeAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.employeeAddress.setGeometry(QtCore.QRect(90, 190, 181, 31))
        self.employeeAddress.setStyleSheet("background-color:white")
        self.employeeAddress.setObjectName("employeeAddress")
        self.employeeEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.employeeEmail.setGeometry(QtCore.QRect(90, 240, 181, 31))
        self.employeeEmail.setStyleSheet("background-color:white")
        self.employeeEmail.setObjectName("employeeEmail")
        self.employeeDepartment = QtWidgets.QLineEdit(self.centralwidget)
        self.employeeDepartment.setGeometry(QtCore.QRect(90, 290, 181, 31))
        self.employeeDepartment.setStyleSheet("background-color:white")
        self.employeeDepartment.setObjectName("employeeDepartment")
        self.employeePosition = QtWidgets.QLineEdit(self.centralwidget)
        self.employeePosition.setGeometry(QtCore.QRect(90, 340, 181, 31))
        self.employeePosition.setStyleSheet("background-color:white")
        self.employeePosition.setObjectName("employeePosition")
        self.employeeSalary = QtWidgets.QLineEdit(self.centralwidget)
        self.employeeSalary.setGeometry(QtCore.QRect(90, 390, 181, 31))
        self.employeeSalary.setStyleSheet("background-color:white")
        self.employeeSalary.setObjectName("employeeSalary")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 120, 131, 16))
        self.label_2.setStyleSheet("font-size:10px\n"
                                   "")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 170, 131, 16))
        self.label_3.setStyleSheet("font-size:10px\n"
                                   "")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 220, 131, 16))
        self.label_4.setStyleSheet("font-size:10px\n"
                                   "")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 270, 131, 16))
        self.label_5.setStyleSheet("font-size:10px\n"
                                   "")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 320, 131, 16))
        self.label_6.setStyleSheet("font-size:10px\n"
                                   "")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 370, 131, 16))
        self.label_7.setStyleSheet("font-size:10px\n"
                                   "")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 420, 131, 16))
        self.label_8.setStyleSheet("font-size:10px\n"
                                   "")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(110, 50, 161, 20))
        self.label_9.setStyleSheet("font-size:18px\n"
                                   "")
        self.label_9.setObjectName("label_9")
        self.employeeAddButton = QtWidgets.QPushButton(self.centralwidget)
        self.employeeAddButton.setGeometry(QtCore.QRect(90, 490, 171, 41))
        self.employeeAddButton.setStyleSheet("background-color: #8d917a;")
        self.employeeAddButton.setObjectName("employeeAddButton")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(500, 50, 161, 20))
        self.label_10.setStyleSheet("font-size:18px\n"
                                    "")
        self.label_10.setObjectName("label_10")
        self.patientAddButton = QtWidgets.QPushButton(self.centralwidget)
        self.patientAddButton.setGeometry(QtCore.QRect(480, 490, 171, 41))
        self.patientAddButton.setStyleSheet("background-color: #8d917a;")
        self.patientAddButton.setObjectName("patientAddButton")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(480, 120, 131, 16))
        self.label_11.setStyleSheet("font-size:10px\n"
                                    "")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(480, 170, 131, 16))
        self.label_12.setStyleSheet("font-size:10px\n"
                                    "")
        self.label_12.setObjectName("label_12")
        self.patientName = QtWidgets.QLineEdit(self.centralwidget)
        self.patientName.setGeometry(QtCore.QRect(480, 90, 181, 31))
        self.patientName.setStyleSheet("background-color:white")
        self.patientName.setObjectName("patientName")
        self.patientAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.patientAddress.setGeometry(QtCore.QRect(480, 190, 181, 31))
        self.patientAddress.setStyleSheet("background-color:white")
        self.patientAddress.setObjectName("patientAddress")
        self.patientBirth = QtWidgets.QLineEdit(self.centralwidget)
        self.patientBirth.setGeometry(QtCore.QRect(480, 140, 181, 31))
        self.patientBirth.setStyleSheet("background-color:white")
        self.patientBirth.setObjectName("patientBirth")
        self.patientEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.patientEmail.setGeometry(QtCore.QRect(480, 240, 181, 31))
        self.patientEmail.setStyleSheet("background-color:white")
        self.patientEmail.setObjectName("patientEmail")
        self.patientPolicy = QtWidgets.QLineEdit(self.centralwidget)
        self.patientPolicy.setGeometry(QtCore.QRect(480, 340, 181, 31))
        self.patientPolicy.setStyleSheet("background-color:white")
        self.patientPolicy.setObjectName("patientPolicy")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(480, 220, 131, 16))
        self.label_13.setStyleSheet("font-size:10px\n"
                                    "")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(480, 320, 131, 16))
        self.label_14.setStyleSheet("font-size:10px\n"
                                    "")
        self.label_14.setObjectName("label_14")
        self.patientPhoneNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.patientPhoneNumber.setGeometry(QtCore.QRect(480, 290, 181, 31))
        self.patientPhoneNumber.setStyleSheet("background-color:white")
        self.patientPhoneNumber.setObjectName("patientPhoneNumber")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(480, 270, 131, 16))
        self.label_16.setStyleSheet("font-size:10px\n"
                                    "")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(480, 370, 131, 16))
        self.label_17.setStyleSheet("font-size:10px\n"
                                    "")
        self.label_17.setObjectName("label_17")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(90, 470, 131, 16))
        self.label_15.setStyleSheet("font-size:10px\n"
                                    "")
        self.label_15.setObjectName("label_15")
        self.employeePhoneNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.employeePhoneNumber.setGeometry(QtCore.QRect(90, 440, 181, 31))
        self.employeePhoneNumber.setStyleSheet("background-color:white")
        self.employeePhoneNumber.setObjectName("employeePhoneNumber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.employeeAddButton.clicked.connect(self.employeeButton)
        self.patientAddButton.clicked.connect(self.patientButton)

    def employeeButton(self):
        data = []
        today = date.today()
        born = self.employeeBirth.text().split('.')
        fullname = self.employeeName.text().split(' ')
        data.extend(fullname)
        data.append(today.year - int(born[2]) - ((today.month, today.day) < (int(born[1]), int(born[0]))))
        data.append(self.employeeAddress.text())
        data.append(self.employeeEmail.text())
        data.append(self.employeePhoneNumber.text())
        data.append(self.employeeDepartment.text())
        data.append(self.employeePosition.text())
        data.append(self.employeeSalary.text())
        print(data)
        insertEmployee(data)


    def patientButton(self):
       data = []
       today = date.today()
       born = self.patientBirth.text().split('.')
       fullname = self.patientName.text().split(' ')
       data.extend(fullname)
       data.append(self.patientAddress.text())
       data.append(today.year - int(born[2]) - ((today.month, today.day) < (int(born[1]), int(born[0]))))
       data.append(self.patientPhoneNumber.text())
       data.append(self.patientEmail.text())
       data.append(self.patientPolicy.text())
       insertPatient(data)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "ФИО "))
        self.label_3.setText(_translate("MainWindow", "Дата рождения"))
        self.label_4.setText(_translate("MainWindow", "Адрес"))
        self.label_5.setText(_translate("MainWindow", "Электронная почта"))
        self.label_6.setText(_translate("MainWindow", "Отделение"))
        self.label_7.setText(_translate("MainWindow", "Должность"))
        self.label_8.setText(_translate("MainWindow", "Зарплата"))
        self.label_9.setText(_translate("MainWindow", "Новый сотрудник"))
        self.employeeAddButton.setText(_translate("MainWindow", "Добавить"))
        self.label_10.setText(_translate("MainWindow", "Новый пациент"))
        self.patientAddButton.setText(_translate("MainWindow", "Добавить"))
        self.label_11.setText(_translate("MainWindow", "ФИО"))
        self.label_12.setText(_translate("MainWindow", "Дата рождения"))
        self.label_13.setText(_translate("MainWindow", "Адрес"))
        self.label_14.setText(_translate("MainWindow", "Номер телефона"))
        self.label_16.setText(_translate("MainWindow", "Электронная почта"))
        self.label_17.setText(_translate("MainWindow", "Номер полиса"))
        self.label_15.setText(_translate("MainWindow", "Номер телефона"))
